// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnW6xTwdoqF-vcF-s6EV-efTW3owa96F4',
    appId: '1:706786632104:web:8903593c73749d21277d9d',
    messagingSenderId: '706786632104',
    projectId: 'mynotes-ea6f3',
    authDomain: 'mynotes-ea6f3.firebaseapp.com',
    storageBucket: 'mynotes-ea6f3.firebasestorage.app',
    measurementId: 'G-6G4R66VEH2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDACX0IUt0rC9axD-3-bBRj-mP1cfc2158',
    appId: '1:706786632104:ios:dc24a7bc830fcc89277d9d',
    messagingSenderId: '706786632104',
    projectId: 'mynotes-ea6f3',
    storageBucket: 'mynotes-ea6f3.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDACX0IUt0rC9axD-3-bBRj-mP1cfc2158',
    appId: '1:706786632104:ios:dc24a7bc830fcc89277d9d',
    messagingSenderId: '706786632104',
    projectId: 'mynotes-ea6f3',
    storageBucket: 'mynotes-ea6f3.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnW6xTwdoqF-vcF-s6EV-efTW3owa96F4',
    appId: '1:706786632104:web:3b2d77870bd7069d277d9d',
    messagingSenderId: '706786632104',
    projectId: 'mynotes-ea6f3',
    authDomain: 'mynotes-ea6f3.firebaseapp.com',
    storageBucket: 'mynotes-ea6f3.firebasestorage.app',
    measurementId: 'G-H8SE61QPV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAlb5EbrZaklQqcZM3ZnohSbdHDQlNpkk',
    appId: '1:706786632104:android:90879d54ec101c15277d9d',
    messagingSenderId: '706786632104',
    projectId: 'mynotes-ea6f3',
    storageBucket: 'mynotes-ea6f3.firebasestorage.app',
  );
}
